version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "period-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dn9trgvzmu0k"
s3_prefix = "period-app"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
